swagger: "2.0"
info:
  description: This is a simple Task Manager
  version: 1.0.0
  title: Task Schedule
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Task
    description: Everthing about task scheduled
schemes:
  - http
paths:
  /tasks:
    post:
      tags:
        - Task
      summary: Add a new task to complete
      description: Create a new task to do
      operationId: createTask
      parameters:
        - in: body
          name: body
          description: new task object that need to be added
          required: true
          schema:
            $ref: "#/definitions/Task"
      responses:
        "201":
          description: Successfully created
          schema:
            $ref: "#/definitions/Task"
        "400":
          description: Bad request

    get:
      tags:
        - Task
      summary: retrive all tasks
      description: retrive all tasks from stored file
      operationId: getAllTasks
      responses:
        "200":
          description: Succesully retrieval of tasks
          schema:
            type: array
            items:
              $ref: "#/definitions/Task"
        "400":
          description: Bad request

  /tasks/{task_id}:
    get:
      tags:
        - Task
      summary: Retrive a single task
      description: Retrive a single task
      operationId: getTask
      parameters:
        - in: path
          name: task_id
          description: id of the task desired to be retrieved
          required: true
          type: string
      responses:
        "200":
          description: Successfully retrieval of task
          schema:
            $ref: "#/definitions/Task"
        "400":
          description: Bad request
        "404":
          description: Task not found

    delete:
      tags:
        - Task
      summary: remove a single task
      description: remove a single task from database
      operationId: removeTask
      parameters:
        - in: path
          name: task_id
          description: id of the task desired to be removed
          required: true
          type: string
      responses:
        "204":
          description: Task successfully deleted, no content returned.
        "400":
          description: Bad request
        "404":
          description: Task not found
    patch:
      tags:
        - Task
      summary: update a single task
      description: update a single task from database
      operationId: updateTask
      parameters:
        - in: path
          name: task_id
          description: id of the task to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Task fields to update
          required: true
          schema:
            $ref: "#/definitions/Task"
      responses:
        '200':
          description: Task updated successfully
          schema:
            $ref: '#/definitions/Task'
        '400':
          description: Bad request
        '404':
          description: Task not found

definitions:
  Task:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      completed:
        type: boolean
